class InternalErrorException(Exception):
    pass

class UserErrorException(Exception):
    pass

class HowIsThisPossibleException(Exception):
    pass